from __future__ import annotations

import json
from typing import Any, Dict, List


import requests

from ..ai.assistant_voice import append_interaction_memory, augment_user_facing_system
from ..ai.user_adaptation import observe_user_message
from ..ai.openrouter_client import (
    DEFAULT_MODEL,
    _extract_json,
    chat_completion_text,
    chat_completion_with_images,
)


def analyze_crash_log(crash_log: str) -> Dict[str, Any]:
    text = crash_log or ""
    lower = text.lower()
    findings: List[str] = []
    suggestions: List[Dict[str, Any]] = []

    if "ars_nouveau" in lower and ("ticking entity" in lower or "particle" in lower):
        findings.append("Likely Ars Nouveau entity/particle issue.")
        suggestions.append(
            {
                "type": "edit_file",
                "path": "config/ars_nouveau-common.toml",
                "new_content": "# Generated by Forager AI\n# Disable heavy particles due to crash signature\nentityParticles = false\n",
            }
        )

    if "create" in lower and ("kinetic" in lower or "stress" in lower):
        findings.append("Create stress/kinetics may be overloading processing.")
        suggestions.append(
            {
                "type": "edit_file",
                "path": "config/create-server.toml",
                "new_content": "# Generated by Forager AI\n# Conservative stress tuning to reduce crash risk\nkineticsStressImpact = 0.9\n",
            }
        )

    if "kubejs" in lower and ("syntax" in lower or "error loading script" in lower):
        findings.append("KubeJS script load error detected.")
        suggestions.append(
            {
                "type": "add_file",
                "path": "kubejs/server_scripts/forager_fixme.js",
                "content": "// Forager AI generated placeholder for KubeJS fix.\n// Review failing scripts and migrate logic incrementally.\n",
            }
        )

    if "crafttweaker" in lower and ("error" in lower or "exception" in lower):
        findings.append("CraftTweaker script error indicated in crash log.")
        suggestions.append(
            {
                "type": "add_file",
                "path": "scripts/forager_fixme.zs",
                "content": "// Forager AI generated placeholder for CraftTweaker fix.\n// Replace problematic recipe removals with guarded checks.\n",
            }
        )

    if "mixin" in lower and "transformer" in lower:
        findings.append("Mixin transformation failure — check recently added mods and their dependency versions.")
    if "java.lang.outofmemoryerror" in lower or "outofmemoryerror" in lower.replace(" ", "") or "java heap space" in lower:
        findings.append("OutOfMemoryError — raise client RAM / tune JVM args; look for memory-heavy mods in the same session.")

    if not findings:
        findings.append("No known signature matched. Start with config sanity checks and mod binary version alignment.")

    feature_plan = {
        "feature_name": "crash_log_hotfix_plan",
        "actions": suggestions,
    }

    return {
        "summary": " ; ".join(findings),
        "findings": findings,
        "feature_plan": feature_plan,
    }


def analyze_crash_log_ai(
    crash_log: str,
    *,
    api_key: str = "",
    pack_context: Dict[str, Any] | None = None,
    model: str = DEFAULT_MODEL,
    images_png: List[bytes] | None = None,
    vision_model: str | None = None,
) -> Dict[str, Any]:
    """Hybrid crash analysis: static signatures first, optional AI enrichment."""
    base = analyze_crash_log(crash_log)
    if crash_log.strip():
        observe_user_message(crash_log[:6000])
    if not api_key.strip() or not crash_log.strip():
        return {
            **base,
            "suspected_mods": [],
            "confidence": "low" if not crash_log.strip() else "medium",
            "ai_used": False,
        }

    system = augment_user_facing_system(
        "You are Forager AI Crash Fix Agent for Minecraft Forge 1.20.1 modpacks. "
        "Return JSON only: {\"summary\":\"string\",\"findings\":[\"string\"],"
        "\"suspected_mods\":[\"string\"],\"confidence\":\"low|medium|high\","
        "\"feature_plan\":{\"feature_name\":\"string\",\"actions\":[{\"type\":\"add_file|edit_file|add_compat|patch_toml|patch_json\","
        "\"path\":\"string\",\"content\":\"string\",\"new_content\":\"string\","
        "\"set_values\":{\"dotted.toml.key\":\"value\"},\"merge\":{\"nested\":\"json_merge\"},"
        "\"rule_name\":\"string\","
        "\"affected_mods\":[\"string\"],\"description\":\"string\"}]}}. "
        "Use patch_toml or patch_json for small config changes instead of replacing whole files when possible. "
        "Prefer safe documentation/add_compat actions unless exact config keys are present."
    )
    user_payload = json.dumps(
        {
            "static_analysis": base,
            "crash_log_excerpt": crash_log[:12000],
            "pack_context": pack_context or {},
            "has_desktop_screenshot": bool(images_png),
        },
        ensure_ascii=True,
    )
    img_list = [b for b in (images_png or []) if isinstance(b, (bytes, bytearray)) and len(b) > 8][:6]
    vr_model = (vision_model or model or DEFAULT_MODEL).strip() or DEFAULT_MODEL
    if img_list:
        system = (
            system
            + " The user attached a desktop screenshot (images after this message). Use visible UI or error text only when it clearly supports the crash log; do not invent mod names from blurry pixels."
        )
    try:
        if img_list:
            raw = chat_completion_with_images(
                api_key=api_key,
                system_prompt=system,
                user_text=user_payload,
                images_png=img_list,
                model=vr_model,
                temperature=0.12,
                timeout_s=120,
                max_tokens=4096,
            )
        else:
            raw = chat_completion_text(
                api_key=api_key,
                system_prompt=system,
                user_text=user_payload,
                model=model,
                temperature=0.12,
                timeout_s=100,
            )
        parsed = _extract_json(raw)
        parsed.setdefault("ai_used", True)
        parsed.setdefault("feature_plan", base["feature_plan"])
        append_interaction_memory(
            source="crash_analysis",
            pack_name=str((pack_context or {}).get("pack_name") or ""),
            summary=str(parsed.get("summary") or ""),
        )
        return parsed
    except (ValueError, json.JSONDecodeError, requests.RequestException, KeyError, OSError):
        return {
            **base,
            "suspected_mods": [],
            "confidence": "medium",
            "ai_used": False,
        }


def crash_followup_checklist(result: Dict[str, Any]) -> List[str]:
    """Human-style next steps after an analysis (deterministic, safe defaults)."""
    steps = [
        "Back up the world or pack if you are about to delete mods or rewrite configs.",
        "Reproduce once so the stack trace matches your real workflow.",
        "Scroll for **Caused by:** lines — root causes are often deeper than the first mod mentioned.",
    ]
    conf = str(result.get("confidence") or "").lower()
    if conf == "low":
        steps.append("Confidence is low: paste a larger log slice (from launch through the error).")
    sm = result.get("suspected_mods") or []
    if isinstance(sm, list) and sm:
        steps.append("Look for mod updates on Modrinth/CurseForge that explicitly support your MC version and loader.")
    else:
        steps.append("If no suspects emerged, verify mod versions match your Minecraft/Forge/Fabric build.")
    plan = result.get("feature_plan")
    if isinstance(plan, dict) and (plan.get("actions") or []):
        steps.append("Review generated file actions in a test instance or backup folder before applying.")
    steps.append("Relaunch in a flat test world before returning to an important save.")
    return steps

