from __future__ import annotations

import base64
import io
import json
import re
import uuid
from typing import Any, Dict, List

from PIL import Image


def image_to_data_url(image: Image.Image) -> str:
    buf = io.BytesIO()
    image.save(buf, format="PNG")
    return "data:image/png;base64," + base64.b64encode(buf.getvalue()).decode("ascii")


def build_bbmodel_project(
    *,
    name: str,
    texture: Image.Image,
    model_type: str = "cube",
    animations: List[Dict[str, Any]] | None = None,
    credit: str = "Generated by Forager AI Texture Forge",
) -> Dict[str, Any]:
    """Return a minimal portable Blockbench project with an embedded texture."""
    clean_name = _clean_name(name)
    width, height = texture.size
    texture_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, f"forager-texture:{clean_name}:{width}x{height}"))
    elements = _elements_for(model_type, texture_uuid)
    project = {
        "meta": {
            "format_version": "5.0",
            "model_format": "free",
            "box_uv": False,
            "backup": False,
        },
        "name": clean_name,
        "credit": credit,
        "resolution": {"width": width, "height": height},
        "elements": elements,
        "outliner": [element["uuid"] for element in elements],
        "textures": [
            {
                "uuid": texture_uuid,
                "id": clean_name,
                "name": f"{clean_name}.png",
                "source": image_to_data_url(texture),
                "width": width,
                "height": height,
                "uv_width": width,
                "uv_height": height,
                "visible": True,
                "mode": "bitmap",
            }
        ],
    }
    timeline = build_animation_timelines(elements, animations or [])
    if timeline:
        project["animations"] = timeline
    return project


def build_animation_timelines(elements: List[Dict[str, Any]], specs: List[Dict[str, Any]]) -> List[Dict[str, Any]]:
    if not elements:
        return []
    animations: List[Dict[str, Any]] = []
    for idx, spec in enumerate(specs[:8]):
        if not isinstance(spec, dict):
            continue
        kind = str(spec.get("animation_kind") or spec.get("kind") or "idle_bob").lower().replace(" ", "_")
        name = _clean_name(str(spec.get("name") or kind or f"animation_{idx}"))
        try:
            length = float(spec.get("length") or spec.get("length_s") or 2.0)
        except (TypeError, ValueError):
            length = 2.0
        length = max(0.25, min(length, 20.0))
        animators: Dict[str, Any] = {}
        for element in elements:
            elem_uuid = str(element.get("uuid") or "")
            if not elem_uuid:
                continue
            animators[elem_uuid] = {
                "name": element.get("name") or "element",
                "type": "bone",
                "keyframes": _keyframes_for(kind, length),
            }
        animations.append(
            {
                "uuid": str(uuid.uuid5(uuid.NAMESPACE_URL, f"forager-animation:{name}:{idx}:{length}")),
                "name": name,
                "loop": "loop" if bool(spec.get("loop", True)) else "once",
                "override": False,
                "length": length,
                "snapping": 24,
                "selected": False,
                "animators": animators,
            }
        )
    return animations


def validate_bbmodel(model: Dict[str, Any]) -> Dict[str, Any]:
    warnings: List[str] = []
    for key in ("meta", "resolution", "elements", "outliner", "textures"):
        if key not in model:
            warnings.append(f"missing {key}")
    if not isinstance(model.get("elements"), list) or not model.get("elements"):
        warnings.append("no model elements")
    textures = model.get("textures") if isinstance(model.get("textures"), list) else []
    if not textures:
        warnings.append("no textures")
    elif not str(textures[0].get("source") or "").startswith("data:image/png;base64,"):
        warnings.append("texture is not embedded as a PNG data URL")
    return {"ok": not warnings, "warnings": warnings}


def bbmodel_to_json(model: Dict[str, Any]) -> str:
    return json.dumps(model, indent=2, ensure_ascii=False)


def _clean_name(value: str) -> str:
    cleaned = re.sub(r"[^A-Za-z0-9_. -]+", "_", str(value or "forager_model")).strip()
    return cleaned[:64] or "forager_model"


def _keyframes_for(kind: str, length: float) -> List[Dict[str, Any]]:
    half = round(length / 2, 3)
    full = round(length, 3)
    if "spin" in kind:
        return [
            _kf("rotation", 0, [0, 0, 0]),
            _kf("rotation", half, [0, 180, 0]),
            _kf("rotation", full, [0, 360, 0]),
        ]
    if "swing" in kind:
        return [
            _kf("rotation", 0, [0, 0, -18]),
            _kf("rotation", half, [0, 0, 18]),
            _kf("rotation", full, [0, 0, -18]),
        ]
    if "pulse" in kind:
        return [
            _kf("scale", 0, [1, 1, 1]),
            _kf("scale", half, [1.08, 1.08, 1.08]),
            _kf("scale", full, [1, 1, 1]),
        ]
    if "walk" in kind:
        return [
            _kf("rotation", 0, [8, 0, 0]),
            _kf("rotation", half, [-8, 0, 0]),
            _kf("rotation", full, [8, 0, 0]),
        ]
    return [
        _kf("position", 0, [0, 0, 0]),
        _kf("position", half, [0, 1, 0]),
        _kf("position", full, [0, 0, 0]),
    ]


def _kf(channel: str, time: float, data_point: List[float]) -> Dict[str, Any]:
    return {
        "channel": channel,
        "time": time,
        "interpolation": "linear",
        "data_points": [{"x": data_point[0], "y": data_point[1], "z": data_point[2]}],
    }


def _elements_for(model_type: str, texture_uuid: str) -> List[Dict[str, Any]]:
    kind = str(model_type or "cube").lower().replace(" ", "_")
    if "slab" in kind:
        return [_cube("slab", [0, 0, 0], [16, 8, 16], texture_uuid)]
    if "pillar" in kind or "column" in kind:
        return [
            _cube("pillar_core", [4, 0, 4], [12, 16, 12], texture_uuid),
            _cube("pillar_top", [2, 14, 2], [14, 16, 14], texture_uuid),
            _cube("pillar_base", [2, 0, 2], [14, 2, 14], texture_uuid),
        ]
    if "handheld" in kind or "tool" in kind:
        return [_cube("handle", [7, 1, 7], [9, 13, 9], texture_uuid), _cube("head", [5, 11, 5], [11, 15, 11], texture_uuid)]
    if "armor" in kind:
        return [
            _cube("helmet", [4, 12, 4], [12, 16, 12], texture_uuid),
            _cube("chest", [3, 6, 4], [13, 12, 12], texture_uuid),
            _cube("arm_l", [1, 6, 5], [3, 12, 11], texture_uuid),
            _cube("arm_r", [13, 6, 5], [15, 12, 11], texture_uuid),
        ]
    if "decor" in kind or "object" in kind:
        return [
            _cube("base", [3, 0, 3], [13, 3, 13], texture_uuid),
            _cube("body", [5, 3, 5], [11, 12, 11], texture_uuid),
            _cube("accent", [6, 12, 6], [10, 15, 10], texture_uuid),
        ]
    if "cross" in kind or "plant" in kind:
        return [_plane("cross_a", [8, 8, 8], [0, 0, 0], texture_uuid), _plane("cross_b", [8, 8, 8], [0, 90, 0], texture_uuid)]
    if "entity" in kind or "mob" in kind:
        return [
            _cube("body", [4, 2, 4], [12, 12, 12], texture_uuid),
            _cube("head", [5, 12, 5], [11, 18, 11], texture_uuid),
            _cube("leg_l", [4, 0, 5], [7, 2, 8], texture_uuid),
            _cube("leg_r", [9, 0, 5], [12, 2, 8], texture_uuid),
        ]
    if "item" in kind or "plane" in kind:
        return [_plane("item_plane", [8, 8, 8], [0, 0, 0], texture_uuid)]
    return [_cube("cube", [0, 0, 0], [16, 16, 16], texture_uuid)]


def _cube(name: str, start: List[float], end: List[float], texture_uuid: str) -> Dict[str, Any]:
    elem_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, f"forager-element:{name}:{start}:{end}"))
    faces = {
        face: {"uv": [0, 0, 16, 16], "texture": texture_uuid}
        for face in ("north", "east", "south", "west", "up", "down")
    }
    return {
        "name": name,
        "type": "cube",
        "uuid": elem_uuid,
        "from": start,
        "to": end,
        "origin": [8, 8, 8],
        "rotation": [0, 0, 0],
        "faces": faces,
    }


def _plane(name: str, origin: List[float], rotation: List[float], texture_uuid: str) -> Dict[str, Any]:
    elem_uuid = str(uuid.uuid5(uuid.NAMESPACE_URL, f"forager-plane:{name}:{rotation}"))
    return {
        "name": name,
        "type": "cube",
        "uuid": elem_uuid,
        "from": [7.9, 0, 0],
        "to": [8.1, 16, 16],
        "origin": origin,
        "rotation": rotation,
        "faces": {
            "east": {"uv": [0, 0, 16, 16], "texture": texture_uuid},
            "west": {"uv": [0, 0, 16, 16], "texture": texture_uuid},
        },
    }
